import { PageHeading } from "../../components";
import { useWorkspace } from "../../context";
import { useI18n } from "../../i18n/context";
import { canConfirmSync } from "../../scheduled/state";

export function Sources() {
  const { t } = useI18n();
  const { state, actions } = useWorkspace();
  const scheduled = state.scheduled;
  const preview = scheduled.syncPreview;
  const canSync = Boolean(scheduled.sourceDocument && preview && canConfirmSync(scheduled, preview.hash));
  const dryRunReady = Boolean(scheduled.sourceDocument && scheduled.source?.mode === "sync" && !preview);
  return <><PageHeading eyebrow={t("scheduled.sources.eyebrow")} title={t("scheduled.sources.title")} description={t("scheduled.sources.description")} />
    <section className="panel source-mode-panel"><div className="source-mode-toolbar"><div className="source-mode-copy"><div className="section-kicker">{t("scheduled.sources.mode")}</div><h2>{scheduled.source?.mode === "sync" ? t("scheduled.sources.syncMode") : t("scheduled.sources.manual")}</h2><p>{t("scheduled.sources.modeDescription")}</p></div><div className="source-mode-switch" role="group" aria-label={t("scheduled.sources.mode")}><button className={`button secondary source-mode-option${scheduled.source?.mode === "manual" ? " active" : ""}`} data-source-mode="manual" aria-pressed={scheduled.source?.mode === "manual"} type="button" disabled={scheduled.source?.mode === "manual"} onClick={() => void actions.setScheduledSourceMode("manual")}>{t("scheduled.sources.manual")}</button><span className="source-mode-switch-arrow" aria-hidden="true">↔</span><button className={`button secondary source-mode-option${scheduled.source?.mode === "sync" ? " active" : ""}`} data-source-mode="sync" aria-pressed={scheduled.source?.mode === "sync"} type="button" disabled={scheduled.source?.mode === "sync"} onClick={() => void actions.setScheduledSourceMode("sync")}>{t("scheduled.sources.syncMode")}</button></div></div></section>
    <section className="panel source-import-panel"><div className="source-import-toolbar"><div className="source-import-copy"><div className="section-kicker">{t("scheduled.sources.file")}</div><h2>{t("scheduled.sources.import")}</h2><p>{t("scheduled.sources.importDescription")}</p></div><div className="source-import-actions"><button className={`button secondary${dryRunReady ? " source-action-ready" : ""}`} type="button" disabled={!scheduled.sourceDocument || scheduled.source?.mode !== "sync"} onClick={() => void actions.previewScheduledSource()}>{t("scheduled.sources.dryRun")}</button><button className="button primary" type="button" disabled={!canSync || scheduled.source?.mode !== "sync"} onClick={() => void actions.syncScheduledSource()}>{t("scheduled.sources.confirmSync")}</button><button className="button secondary source-tool-button" type="button" onClick={() => void actions.exportScheduledSource()}>{t("scheduled.sources.export")}</button><button className="button secondary source-tool-button" type="button" onClick={() => void actions.snapshotScheduledSource()}>{t("scheduled.sources.snapshot")}</button></div></div><div className="file-input"><span>{t("scheduled.sources.file")}</span><div className="source-file-picker"><label className="button secondary" data-source-file-picker><input data-source-file-input type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void actions.loadScheduledSourceFile(file); }} /><span>{t("scheduled.sources.chooseFile")}</span></label><span className="source-file-name" aria-live="polite">{scheduled.sourceDocument ? t("scheduled.sources.fileReady") : t("scheduled.sources.noFile")}</span></div></div>{scheduled.sourceDocument && <div className="source-document"><code>{scheduled.sourceDocument.hash}</code></div>}</section>
    {preview && <section className="panel source-preview-panel"><div className="panel-header"><div className="panel-title"><div><h2>{t("scheduled.sources.preview")}</h2><p><code>{preview.hash}</code></p></div></div></div><div className="detail-grid"><Diff label={t("scheduled.sources.added")} value={preview.diff.added} /><Diff label={t("scheduled.sources.updated")} value={preview.diff.updated} /><Diff label={t("scheduled.sources.removed")} value={preview.diff.removed} /><Diff label={t("scheduled.sources.unchanged")} value={preview.diff.unchanged} /></div></section>}
  </>;
}

function Diff({ label, value }: { label: string; value: number }) { return <div className="detail-item"><label>{label}</label><strong>{value}</strong></div>; }
