import { pageHeading, pagination } from "../components.js";
import { escapeAttribute, escapeHtml, liveTime } from "../formatters.js";
import { SNAPSHOTS_PAGE_SIZE, pageInfo } from "../state.js";

export function renderConfiguration(state) {
  const settings = state.settings;
  const snapshots = settings.snapshots || [];
  const page = pageInfo(snapshots, state.pagination.snapshots, SNAPSHOTS_PAGE_SIZE);
  state.pagination.snapshots = page.page;
  const current = settings.config.timezone || "";
  return `${pageHeading("Workspace / Configuration", "Configuration", "Manage timezone behavior and recoverable configuration snapshots.", '<button class="button secondary" data-action="refresh">Refresh</button>')}<div class="config-layout"><section class="panel config-card"><div class="panel-header"><div class="panel-title"><div><h2>Timezone</h2><p>Effective: ${escapeHtml(settings.effective_timezone.name)}</p></div></div></div><form class="timezone-form" id="timezone-form"><label for="timezone-input">IANA timezone</label><input class="text-input" id="timezone-input" list="timezone-list" value="${escapeAttribute(current)}" placeholder="Asia/Tokyo"><datalist id="timezone-list">${settings.timezones.map((value) => `<option value="${escapeAttribute(value)}"></option>`).join("")}</datalist><div class="dialog-actions"><button class="button secondary" data-action="unset-timezone" type="button">Use system</button><button class="button primary" type="submit">Save timezone</button></div></form></section><section class="panel config-card"><div class="panel-header"><div class="panel-title"><div><h2>Configuration snapshots</h2><p>Restore a known configuration safely.</p></div></div><button class="button small secondary" data-action="create-snapshot">Create snapshot</button></div><div class="snapshot-list">${page.items.map((snapshot) => `<div class="snapshot-row"><div><strong>${snapshot.valid ? "Valid snapshot" : "Invalid snapshot"}</strong><small>${liveTime(snapshot.created_at, state.timezone?.name)} · ${escapeHtml(snapshot.reason || "unknown")}</small><code>${escapeHtml(snapshot.path)}</code></div><button class="button small secondary" data-restore-path="${escapeAttribute(snapshot.path)}" ${snapshot.valid ? "" : "disabled"}>Restore</button></div>`).join("") || '<div class="empty-state"><strong>No snapshots yet</strong></div>'}</div>${pagination("snapshots", page)}<div class="config-paths"><span>Config: <code>${escapeHtml(settings.config_path)}</code></span><span>Snapshots: <code>${escapeHtml(settings.snapshot_dir)}</code></span></div></section></div><section class="panel config-card"><div class="panel-header"><div class="panel-title"><div><h2>Current config</h2><p>Equivalent to <code>stoker config show</code>.</p></div></div></div><pre class="config-json">${escapeHtml(JSON.stringify(settings.config, null, 2))}</pre></section>`;
}
