import { escapeAttribute, escapeHtml, shortId, stateBadge } from "../formatters.js";

export function renderQueue(state) {
  const jobs = state.queue.jobs || [];
  const locked = Boolean(state.queue.locked);
  const rows = jobs.length ? jobs.map((job, index) => `<tr><td class="mono">${index + 1}</td><td><div class="job-name"><strong>${escapeHtml(job.name)}</strong><small>${escapeHtml(shortId(job.id))}</small></div></td><td>${escapeHtml(job.user)}</td><td class="path-cell" title="${escapeAttribute(job.cwd)}">${escapeHtml(job.cwd)}</td><td>${stateBadge(job.state)}</td><td><div class="move-controls"><button class="move-button" type="button" data-queue-move="${escapeAttribute(job.id)}" data-target-order="${index}" aria-label="Move ${escapeAttribute(job.name)} up" ${!locked || index === 0 ? "disabled" : ""}>↑</button><button class="move-button" type="button" data-queue-move="${escapeAttribute(job.id)}" data-target-order="${index + 2}" aria-label="Move ${escapeAttribute(job.name)} down" ${!locked || index === jobs.length - 1 ? "disabled" : ""}>↓</button></div></td></tr>`).join("") : '<tr><td colspan="6"><div class="empty-state"><div class="empty-icon">○</div><strong>The queue is clear. Commit a DRAFT job from the Jobs view or CLI.</strong></div></td></tr>';
  return `
    <div class="page-heading"><div><div class="eyebrow">Workspace / Queue</div><h1>Execution queue</h1><p>Lock the global queue before changing its order. Every move is checked against the server’s latest state.</p></div><div class="page-actions"><button class="button secondary" data-action="refresh">Refresh queue <span aria-hidden="true">↻</span></button><button class="button primary" data-queue-lock="true" ${locked ? "disabled" : ""}>Lock queue</button><button class="button secondary" data-queue-lock="false" ${locked ? "" : "disabled"}>Unlock queue</button></div></div>
    ${locked ? '<div class="queue-lock-banner"><div><strong>Queue is locked</strong><small>This global lock is visible to every connected client. Use the arrows below to adjust order.</small></div><span aria-hidden="true">🔒</span></div>' : '<div class="queue-unlock-banner"><div><strong>Queue is unlocked</strong><small>Lock the queue to enable reorder controls and prevent the scheduler from claiming work during edits.</small></div><span aria-hidden="true">↕</span></div>'}
    <section class="panel"><div class="panel-header"><div class="panel-title"><div><h2>${jobs.length} queued job${jobs.length === 1 ? "" : "s"}</h2><p>Ordered by queue position · server state</p></div></div></div><div class="queue-table"><table class="data-table queue-order-table"><thead><tr><th>#</th><th>Job name</th><th>Owner</th><th>Path</th><th>State</th><th>Move</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
}
