import { useState } from "react";
import { PageHeading, EmptyState, LiveTime, Pagination } from "../components";
import { SNAPSHOTS_PAGE_SIZE, pageInfo, useWorkspace } from "../context";

export function Configuration() {
  const { state, actions } = useWorkspace();
  const [showSuggestions, setShowSuggestions] = useState(false);
  const settings = state.settings;
  if (!settings) return <div className="page-loading"><span className="spinner"></span><span>Loading configuration…</span></div>;
  const snapshots = settings.snapshots || [];
  const page = pageInfo(snapshots, state.pagination.snapshots, SNAPSHOTS_PAGE_SIZE);
  const current = typeof settings.config.timezone === "string" ? settings.config.timezone : "";
  const configured = state.configurationDraft === null ? current : state.configurationDraft;
  const timezone = settings.effective_timezone || { name: "—", source: "—" };
  const query = configured.trim().toLowerCase();
  const suggestions = query ? settings.timezones.filter((zone) => zone.toLowerCase().includes(query)).slice(0, 8) : [];
  const exact = settings.timezones.includes(configured.trim());
  const changed = configured.trim() !== current;
  return <>
    <PageHeading eyebrow="Workspace / Configuration" title="Workspace settings" description="Manage the same timezone and configuration snapshots available from the CLI." actions={<button className="button secondary" data-action="refresh" onClick={() => void actions.loadData()}>Refresh configuration <span aria-hidden="true">↻</span></button>} />
    <div className="config-layout"><section className="panel config-card"><div className="panel-header"><div className="panel-title"><div><h2>Timezone</h2><p>Used when displaying timestamps in the UI and CLI.</p></div></div></div><div className="config-summary"><div><span className="config-label">Effective timezone</span><strong>{timezone.name}</strong></div><div><span className="config-label">Source</span><span className="config-value">{timezone.source}</span></div><div><span className="config-label">Configured value</span><span className="config-value">{configured || "Not set · follows system"}</span></div></div><form className="config-form" id="timezone-form" onSubmit={(event) => { event.preventDefault(); if (exact && changed) void actions.saveTimezone(configured.trim()); }}><label htmlFor="timezone-input">Set IANA timezone</label><div className="timezone-picker"><input className="text-input" id="timezone-input" name="timezone" value={configured} placeholder="Type Tokyo, Taipei, UTC…" autoComplete="off" role="combobox" aria-autocomplete="list" aria-controls="timezone-suggestions" aria-expanded={showSuggestions && suggestions.length > 0} onFocus={() => setShowSuggestions(true)} onChange={(event) => { actions.setConfigurationDraft(event.target.value); setShowSuggestions(true); }} /><div className={`timezone-suggestions${showSuggestions && suggestions.length ? " visible" : ""}`} id="timezone-suggestions" role="listbox">{suggestions.map((zone) => <button className="timezone-option" type="button" role="option" data-timezone={zone} key={zone} onClick={() => { actions.setConfigurationDraft(zone); setShowSuggestions(false); }}>{zone}</button>)}</div></div><div id="timezone-feedback" className={`form-feedback ${exact && changed ? "valid" : configured ? "invalid" : ""}`} aria-live="polite">{exact && changed ? "✓ Valid timezone. Ready to save." : exact ? "Current timezone is already selected." : configured ? "Choose a timezone from the suggestions." : "Start typing to search available timezones."}</div><div className="form-row"><button className="button primary" id="timezone-set" type="submit" disabled={!exact || !changed}>Set timezone</button><button className="button secondary" data-action="unset-timezone" type="button" onClick={() => void actions.unsetTimezone()}>Use system</button></div><small className="form-help">Type to search {settings.timezones.length} IANA timezones, then click a suggestion or press Enter.</small></form></section>
      <section className="panel config-card"><div className="panel-header"><div className="panel-title"><div><h2>Configuration snapshots</h2><p>Restore a known configuration without touching jobs.</p></div></div><button className="button small secondary" data-action="create-snapshot" type="button" onClick={() => void actions.createSnapshot()}>Create snapshot</button></div><div className="snapshot-list">{page.items.length ? page.items.map((snapshot) => <div className="snapshot-row" key={snapshot.path}><div className="snapshot-copy"><strong>{snapshot.created_at ? <LiveTime value={snapshot.created_at} timezone={state.timezone?.name} /> : "Invalid snapshot"}</strong><small>{snapshot.reason || snapshot.error || snapshot.path}</small></div><div className="snapshot-actions">{snapshot.valid ? <button className="button small secondary" type="button" data-restore-path={snapshot.path} onClick={() => void actions.restoreSnapshot(snapshot.path)}>Restore</button> : <span className="state-badge state-failed">Invalid</span>}</div></div>) : <EmptyState compact title="No snapshots yet" message="Save a manual snapshot before making a configuration change." />}</div><Pagination kind="snapshots" page={page} onPage={(next) => actions.setPage("snapshots", next)} /><div className="config-paths"><span>Config: <code>{settings.config_path}</code></span><span>Snapshots: <code>{settings.snapshot_dir}</code></span></div></section></div>
    <section className="panel config-card"><div className="panel-header"><div className="panel-title"><div><h2>Current config</h2><p>Equivalent to <code>stoker config show</code>.</p></div></div></div><pre className="config-json">{JSON.stringify(settings.config, null, 2)}</pre></section>
  </>;
}
