import { useEffect, useState } from "react";
import { EmptyState, JobRow, LiveTime, Pagination, StateBadge } from "../components";
import { isTerminalState, limitUnicode } from "../formatters";
import { JOBS_PAGE_SIZE, pageInfo, useWorkspace } from "../context";
import type { Job, PageInfo } from "../types";

const JOB_STATES = ["DRAFT", "QUEUED", "STARTING", "RUNNING", "CANCELLING", "SUCCEEDED", "FAILED", "CANCELLED", "LOST"];

export function Jobs() {
  const { state, actions } = useWorkspace();
  const query = state.filters.search.toLowerCase();
  const filtered = state.jobs.filter((job) => {
    const matchesSearch = !query || [job.name, job.user, job.cwd, job.id].some((value) => String(value || "").toLowerCase().includes(query));
    return matchesSearch && (!state.filters.user || job.user === state.filters.user) && (!state.filters.state || job.state === state.filters.state);
  });
  const page = pageInfo(filtered, state.pagination.jobs, JOBS_PAGE_SIZE);
  const owners = [...new Set(state.jobs.map((job) => job.user))].sort();
  const terminalCount = state.jobs.filter((job) => isTerminalState(job.state)).length;
  return <>
    <div className="page-heading"><div><div className="eyebrow">Workspace / Jobs</div><h1>All jobs</h1><p>Search every submission, inspect its working directory, and keep an eye on its lifecycle.</p></div><div className="page-actions"><button className="button primary" data-action="new-job" type="button" onClick={() => void actions.openJobForm()}>＋ New job</button><button className="button secondary" data-action="refresh" onClick={() => void actions.loadData()}>Refresh jobs <span aria-hidden="true">↻</span></button><button className="button danger" data-action="clean-jobs" type="button" disabled={!terminalCount} onClick={() => void actions.cleanJobs()}>Clean job history{terminalCount ? ` (${terminalCount})` : ""}</button></div></div>
    <div className="toolbar"><input className="search-input" id="job-search" type="search" autoComplete="off" spellCheck={false} placeholder="Search job name, owner, ID, or path" value={state.filters.search} aria-label="Search jobs" onChange={(event) => actions.setFilter("search", event.target.value)} /><div className="filter-group"><select className="select-input" id="user-filter" aria-label="Filter by owner" value={state.filters.user} onChange={(event) => actions.setFilter("user", event.target.value)}><option value="">All owners</option>{owners.map((owner) => <option value={owner} key={owner}>{owner}</option>)}</select><select className="select-input" id="state-filter" aria-label="Filter by state" value={state.filters.state} onChange={(event) => actions.setFilter("state", event.target.value)}><option value="">All states</option>{JOB_STATES.map((value) => <option value={value} key={value}>{value}</option>)}</select></div></div>
    <section className="panel"><div className="panel-header"><div className="panel-title"><div><h2>{filtered.length} visible job{filtered.length === 1 ? "" : "s"}</h2><p>Server state · <LiveTime value={new Date()} timezone={state.timezone?.name} /></p></div></div></div><div className="table-wrap"><table className="data-table jobs-table"><thead><tr><th>Job name</th><th>Owner</th><th>Path</th><th>State</th><th>Queue</th><th>Created</th></tr></thead><tbody>{page.items.length ? page.items.map((job) => <JobRow job={job} timezone={state.timezone?.name} onOpen={actions.openJobDetail} key={job.id} />) : <tr><td colSpan={6}><EmptyState icon="○" title="No jobs match these filters" /></td></tr>}</tbody></table></div><Pagination kind="jobs" page={page} onPage={(next) => actions.setPage("jobs", next)} /></section>
  </>;
}

export function JobForm() {
  const { state, actions, jobFormOpen } = useWorkspace();
  const [showOwners, setShowOwners] = useState(false);
  useEffect(() => { if (!jobFormOpen) setShowOwners(false); }, [jobFormOpen]);
  const limits = { name: state.config?.max_job_name_length || 128, user: state.config?.max_job_user_length || 50, description: state.config?.max_job_description_length || 200 };
  const draft = state.jobDraft;
  const browser = state.filesystem.current;
  const owners = [...new Set(state.jobs.map((job) => job.user).filter(Boolean))].filter((owner) => !draft.user || owner.toLowerCase().includes(draft.user.trim().toLowerCase())).sort().slice(0, 50);
  return <div className="dialog-card job-card"><div className="dialog-kicker">Workspace / Jobs</div><div className="job-dialog-heading"><div><h2 id="job-dialog-title">New job</h2><p>Create a draft job. Commit it when you're ready to run.</p></div><button className="dialog-close" data-action="close-job-form" type="button" aria-label="Close new job" onClick={actions.closeJobForm}>×</button></div>
    <form id="new-job-form" noValidate onSubmit={(event) => { event.preventDefault(); void actions.saveJob(); }}>
      <div className="job-form-grid"><div className="job-field"><label htmlFor="job-user">Owner</label><div className="job-user-picker"><input className="text-input" id="job-user" maxLength={limits.user} value={draft.user} autoComplete="off" autoCapitalize="off" aria-autocomplete="list" aria-controls="job-user-suggestions" aria-expanded={showOwners && owners.length > 0} required onFocus={() => setShowOwners(true)} onChange={(event) => { setShowOwners(true); actions.updateDraft({ user: event.target.value }); }} /><div className={`job-suggestions${showOwners && owners.length ? " visible" : ""}`} id="job-user-suggestions" role="listbox">{showOwners && owners.length > 0 && <><div className="job-suggestions-label">Known owners · {owners.length}</div>{owners.map((owner) => <button className="job-suggestion" type="button" role="option" data-job-user={owner} key={owner} onClick={() => { actions.updateDraft({ user: owner }); setShowOwners(false); }}><span className="suggestion-avatar">{owner.slice(0, 1).toUpperCase()}</span><span>{owner}</span></button>)}</>}</div></div><small className="form-help">Maximum {limits.user} characters.</small></div><div className="job-field"><label htmlFor="job-name">Job name</label><input className="text-input" id="job-name" maxLength={limits.name} value={draft.name} autoComplete="off" required onChange={(event) => actions.updateDraft({ name: event.target.value })} /><small className="form-help">Maximum {limits.name} characters.</small></div></div>
      <div className="job-field"><label htmlFor="job-cwd">Working directory</label><div className="path-input-row"><input className="text-input mono-input" id="job-cwd" value={draft.cwd} placeholder="Choose a folder on the Stoker host" autoComplete="off" autoCapitalize="off" spellCheck={false} required onChange={(event) => actions.updateDraft({ cwd: event.target.value })} /><button className="button secondary" data-action="browse-directory" type="button" onClick={() => void actions.loadDirectory(draft.cwd || state.filesystem.roots?.default_path || "")}>Browse</button></div><small className="form-help">Folders are read from the Stoker host.</small></div>
      {(browser || state.filesystem.loading) && <div className="fs-browser"><div className="fs-path-row"><input className="text-input" id="fs-path" value={state.filesystem.inputPath || browser?.path || ""} onChange={(event) => actions.setFilesystemInputPath(event.target.value)} /><button className="button secondary" data-action="open-directory" type="button" onClick={() => void actions.loadDirectory(state.filesystem.inputPath)}>Open</button></div>{state.filesystem.error && <div className="form-feedback invalid">{state.filesystem.error}</div>}<div className="fs-directory-list">{state.filesystem.loading ? <EmptyState icon="⌁" title="Loading directories" /> : browser?.directories.length ? browser.directories.map((entry) => <button className="fs-directory-row" type="button" data-directory={entry.path} key={entry.path} onClick={() => void actions.loadDirectory(entry.path)}><span className="fs-folder-glyph">◆</span><span>{entry.name}</span><span className="fs-row-arrow">›</span></button>) : <EmptyState icon="○" title="No subdirectories" />}</div>{browser && <button className="button small primary" data-action="choose-directory" type="button" onClick={actions.chooseDirectory}>Use this directory</button>}</div>}
      <div className="job-field"><label htmlFor="job-command">Command</label><textarea className="command-input" id="job-command" rows={4} placeholder="cargo build --release" value={draft.command} required onChange={(event) => actions.updateDraft({ command: event.target.value })} /><small className="form-help">Enter the command only; Stoker will keep the same quoting rules as <code>stoker add --cmd</code>.</small></div>
      <div className="job-field"><label htmlFor="job-description">Description <span className="field-optional">Optional</span></label><textarea className="description-input" id="job-description" rows={4} maxLength={limits.description} placeholder="What is this job for?" value={draft.description} onChange={(event) => actions.updateDraft({ description: event.target.value })} /><small className="form-help">Maximum {limits.description} characters. <span id="job-description-count">{[...draft.description].length}/{limits.description}</span></small></div>
      <div className={`form-feedback${state.filesystem.error ? " invalid" : ""}`} aria-live="polite">{state.filesystem.error}</div><div className="dialog-actions"><button className="button secondary" data-action="close-job-form" type="button" onClick={actions.closeJobForm}>Cancel</button><button className="button primary" type="submit">Create draft</button></div>
    </form>
  </div>;
}

export function JobDetail() {
  const { state, actions, detailEditing } = useWorkspace();
  const job = state.selectedJob;
  const detail = state.selectedJobDetail;
  const [description, setDescription] = useState(job?.description || "");
  useEffect(() => { if (!detailEditing) setDescription(job?.description || ""); }, [detailEditing, job?.description]);
  if (!job) return <div className="job-detail-card"><EmptyState icon="○" title="Loading job…" /></div>;
  const canCommit = job.state === "DRAFT";
  const canCancel = ["DRAFT", "QUEUED", "STARTING", "RUNNING"].includes(job.state);
  const command = job.command_line || job.command?.join(" ") || "—";
  const directoryStatus = detail?.working_directory_status || (["RUNNING", "STARTING", "CANCELLING"].includes(job.state) ? "Used by the active process" : "Stored submission path");
  const timeline: Array<[string, string | null | undefined]> = [["Created", job.created_at], ["Committed", job.committed_at], ["Started", job.started_at], ["Finished", job.finished_at]];
  return <div className="job-detail-card"><div className="job-detail-heading"><div><div className="dialog-kicker">Workspace / Jobs</div><h2 id="job-detail-title">{job.name}</h2><p className="job-detail-id mono"><span>{job.id}</span><button className="copy-id-button" data-action="copy-job-id" data-job-id={job.id} type="button" title="Copy job ID" aria-label="Copy job ID" onClick={() => void actions.copyJobId(job.id)}></button></p></div><button className="dialog-close" data-action="close-job-detail" type="button" aria-label="Close job details" onClick={actions.closeJobDetail}>×</button></div>
    <div className="job-detail-status"><div><span className="section-kicker">Current state</span><div className="job-detail-state"><StateBadge value={job.state} /></div></div><div className="job-detail-status-meta"><span className="job-detail-directory-status">{directoryStatus}</span></div></div>
    <section className="job-detail-section"><div className="section-kicker">Job overview</div><div className="job-detail-grid"><div><span className="detail-label">Owner</span><strong>{job.user}</strong></div><div><span className="detail-label">Queue order</span><strong>{job.queue_order ?? "—"}</strong></div><div className="job-detail-wide"><span className="detail-label">Working directory</span><code>{job.cwd}</code></div><div className="job-detail-wide"><span className="detail-label">Command</span><pre className="job-command">{command}</pre></div></div></section>
    <section className="job-detail-section job-description-section"><div className="section-heading-row"><div className="section-kicker">Description</div><button className="button small secondary" data-action="edit-description" type="button" onClick={actions.toggleDescriptionEdit}>{detailEditing ? "Cancel" : (job.description ? "Edit" : "Add description")}</button></div>{detailEditing ? <form id="description-form" onSubmit={(event) => { event.preventDefault(); void actions.saveDescription(description); }}><textarea className="description-input job-description-editor" id="description-input" maxLength={state.config?.max_job_description_length || 200} rows={5} value={description} onChange={(event) => setDescription(event.target.value)} /><div className="description-editor-meta"><small className="form-help">{[...description].length}/{state.config?.max_job_description_length || 200}</small><div className="description-editor-actions"><button className="button small primary" type="submit">Save</button></div></div></form> : <p className={`job-description-preview${job.description ? "" : " empty"}`}>{limitUnicode(job.description || "No description provided.", 1000)}</p>}</section>
    <section className="job-detail-section"><div className="timeline-heading"><div className="section-kicker">Timeline</div>{detail?.display_timezone && <span className="job-detail-timezone">Times shown in {detail.display_timezone}</span>}</div><div className="job-timeline">{timeline.map(([label, value]) => <div className={`timeline-item${value ? " has-value" : ""}`} key={label}><span className="timeline-dot" aria-hidden="true"></span><span className="timeline-label">{label}</span><span className="timeline-time">{value ? <LiveTime value={value} timezone={state.timezone?.name} /> : "Not recorded"}</span></div>)}</div></section>
    <div className="job-detail-actions"><button className="button secondary" data-action="view-job-logs" data-job-id={job.id} onClick={() => void actions.viewJobLogs(job.id)}>View logs</button><span className="job-action-spacer"></span>{canCommit && <button className="button primary" data-job-action="commit" data-job-id={job.id} onClick={() => void actions.commitJob(job.id)}>Commit job</button>}{canCancel && !isTerminalState(job.state) && <button className="button danger" data-job-action="cancel" data-job-id={job.id} onClick={() => void actions.cancelJob(job.id)}>Cancel job</button>}</div>
  </div>;
}

export type JobsPageInfo = PageInfo<Job>;
